# Generated by Django 4.0.3 on 2022-05-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='img',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
